CXX=c++
NAME=PmergeMe
CXXFLAGS+=-O3 -MD -std=c++98 -Werror -Wall -Wextra -pedantic-errors -Wcast-align -Wcast-qual -Wconversion -Wctor-dtor-privacy -Wdisabled-optimization -Wdouble-promotion -Weffc++ -Werror -Wfloat-equal -Wformat=2 -Winit-self -Wint-to-pointer-cast -Wmissing-include-dirs -Wnon-virtual-dtor -Wno-unused -Wnull-dereference -Wold-style-cast -Woverloaded-virtual -Wpedantic -Wpointer-arith -Wredundant-decls -Wsequence-point -Wshadow -Wsign-conversion -Wsign-promo -Wstrict-overflow=5 -Wswitch -Wswitch-default -Wundef -Wunreachable-code -Wunused -Wwrite-strings
# -Wmissing-declarations
SRC=main.cpp PmergeMe.cpp
OBJ=$(SRC:.cpp=.o)
DEPS=$(SRC:.cpp=.d)
all:$(NAME)
$(NAME):$(OBJ)
	$(CXX) $(LDFLAGS) $(LDLIBS) -o $@ $^
%.o:%.cpp
	$(CXX) -c $(CXXFLAGS) $(CPPFLAGS) -o $@ $<
-include $(DEPS)
clean:
	$(RM) $(OBJ) $(DEPS)
fclean:clean
	$(RM) $(NAME)
re:fclean
	$(MAKE) all
debug_vector:
	CXXFLAGS=-DDEBUG_VECTOR $(MAKE) re
debug_list:
	CXXFLAGS=-DDEBUG_LIST $(MAKE) re
.PHONY:all clean fclean re
